;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Action.Secondary.Parry",DevComment="")
+GameplayTagList=(Tag="Character.Class.Gunslinger",DevComment="")
+GameplayTagList=(Tag="HitScan",DevComment="")
+GameplayTagList=(Tag="Projectile",DevComment="")
+GameplayTagList=(Tag="Style.Category.Heavy",DevComment="")
+GameplayTagList=(Tag="Style.Category.Light",DevComment="")
+GameplayTagList=(Tag="Weapon.CanFire",DevComment="")
+GameplayTagList=(Tag="Weapon.Capability.CanCrit",DevComment="")
+GameplayTagList=(Tag="Weapon.Capability.HasSecondaryAttack",DevComment="")
+GameplayTagList=(Tag="Weapon.Slot.Primary",DevComment="")
+GameplayTagList=(Tag="Weapon.Slot.Secondary",DevComment="")
+GameplayTagList=(Tag="Weapon.Type.Charged",DevComment="")
+GameplayTagList=(Tag="Weapon.Type.Melee",DevComment="")
+GameplayTagList=(Tag="Weapon.Type.Ranged",DevComment="")

